apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: adot-collector-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "nodes/proxy", "nodes/stats"]
  verbs: ["get", "list", "watch"]
