apiVersion: v1
kind: ConfigMap
metadata:
  name: adot-collector-fargate-config
  namespace: adot-col-fargate
data:
  adot-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:
    exporters:
      awsemf:
        region: "us-east-1"
        namespace: "ContainerInsights/Fargate"
        log_group_name: '/aws/containerinsights/protein-engineering-cluster-new/performance'
        log_stream_name: 'fargate-adot-collector'
        resource_to_telemetry_conversion:
          enabled: true
        dimension_rollup_option: NoDimensionRollup
        metric_declarations:
          - dimensions: [[PodName, Namespace, ClusterName]]
            metric_name_selectors:
              - ^container_cpu_usage_seconds_total$
              - ^container_memory_working_set_bytes$
              - ^container_network_receive_bytes_total$
              - ^container_network_transmit_bytes_total$
          - dimensions: [[Service, Namespace, ClusterName]]
            metric_name_selectors:
              - ^service_number_of_running_pods$
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [awsemf]
