apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: adot-collector-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: adot-collector
  namespace: amazon-cloudwatch
roleRef:
  kind: ClusterRole
  name: adot-collector-clusterrole
  apiGroup: rbac.authorization.k8s.io
