apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"labels":{"app":"aws-adot","component":"adot-collector"},"name":"adot-collector","namespace":"amazon-cloudwatch"},"spec":{"selector":{"matchLabels":{"app":"aws-adot","component":"adot-collector"}},"serviceName":"adot-collector-service","template":{"metadata":{"labels":{"app":"aws-adot","component":"adot-collector"}},"spec":{"containers":[{"command":["/awscollector","--config=/conf/adot-collector-config.yaml"],"env":[{"name":"OTEL_RESOURCE_ATTRIBUTES","value":"ClusterName=protein-engineering-cluster-new"}],"image":"public.ecr.aws/aws-observability/aws-otel-collector:latest","imagePullPolicy":"Always","name":"adot-collector","resources":{"limits":{"cpu":1,"memory":"2Gi"},"requests":{"cpu":1,"memory":"2Gi"}},"volumeMounts":[{"mountPath":"/conf","name":"adot-collector-config-volume"}]}],"securityContext":{"fsGroup":65534},"serviceAccountName":"adot-collector","volumes":[{"configMap":{"items":[{"key":"adot-collector-config","path":"adot-collector-config.yaml"}],"name":"adot-collector-config"},"name":"adot-collector-config-volume"}]}}}}
  creationTimestamp: "2024-10-15T15:10:54Z"
  generation: 10
  labels:
    app: aws-adot
    component: adot-collector
  name: adot-collector
  namespace: amazon-cloudwatch
  resourceVersion: "129589496"
  uid: d39d5643-a590-4094-b8c3-21a03710f1c5
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: aws-adot
      component: adot-collector
  serviceName: adot-collector-service
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-10-15T23:25:31Z"
      creationTimestamp: null
      labels:
        app: aws-adot
        component: adot-collector
    spec:
      containers:
      - command:
        - /awscollector
        - --config=/conf/adot-collector-config.yaml
        env:
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: ClusterName=protein-engineering-cluster-new
        image: public.ecr.aws/aws-observability/aws-otel-collector:latest
        imagePullPolicy: Always
        name: adot-collector
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /conf
          name: adot-collector-config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 65534
      serviceAccount: adot-collector
      serviceAccountName: adot-collector
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: adot-collector-config
            path: adot-collector-config.yaml
          name: adot-collector-config
        name: adot-collector-config-volume
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  availableReplicas: 1
  collisionCount: 0
  currentReplicas: 1
  currentRevision: adot-collector-5d4c4689f8
  observedGeneration: 10
  readyReplicas: 1
  replicas: 1
  updateRevision: adot-collector-5d4c4689f8
  updatedReplicas: 1
