apiVersion: v1
kind: ConfigMap
metadata:
  name: adot-collector-conf
  namespace: amazon-cloudwatch
data:
  adot-collector-config: |
    receivers:
      awscontainerinsightreceiver:
        collection_interval: 30s
        container_orchestrator: eks
        add_service_as_attribute: true
        prefer_full_pod_name: true
        enable_control_plane_metrics: false
        fargate_mode: true
    processors:
      batch:
    exporters:
      awsemf:
        namespace: ContainerInsights
        log_group_name: '/aws/containerinsights/{ClusterName}/performance'
        log_stream_name: '{PodName}'
        resource_to_telemetry_conversion:
          enabled: true
        dimension_rollup_option: NoDimensionRollup
        parse_json_encoded_attr_values: [Sources, kubernetes]
        metric_declarations:
          - dimensions: [[PodName, Namespace, ClusterName], [Service, Namespace, ClusterName], [Namespace, ClusterName], [ClusterName]]
            metric_name_selectors:
              - pod_cpu_utilization
              - pod_memory_utilization
              - pod_network_rx_bytes
              - pod_network_tx_bytes
              - pod_cpu_utilization_over_pod_limit
              - pod_memory_utilization_over_pod_limit
              - number_of_running_pods
              - number_of_container_restarts
    service:
      pipelines:
        metrics:
          receivers: [awscontainerinsightreceiver]
          processors: [batch]
          exporters: [awsemf]
