apiVersion: v1
kind: Service
metadata:
  name: adot-collector
  namespace: fargate-container-insights
spec:
  selector:
    app: adot-collector
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
  - name: otlp-http
    port: 4318
    targetPort: 4318
