apiVersion: v1
kind: ConfigMap
metadata:
  name: adot-collector-config
  namespace: fargate-container-insights
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
      filterprocessor/namespace_bioapptives:
        logs:
          include:
            match_type: strict
            attributes:
              - key: k8s.namespace.name
                value: bioapptives
      filterprocessor/namespace_marcador:
        logs:
          include:
            match_type: strict
            attributes:
              - key: k8s.namespace.name
                value: marcador
      filterprocessor/errors:
        logs:
          include:
            match_type: regexp
            attributes:
              - key: message
                value: ".*(OperationalError|Name or service not known|Connection reset by peer).*"
    exporters:
      awsemf/bioapptives:
        region: '${AWS_REGION}'
        log_group_name: '/aws/eks/${CLUSTER_NAME}/bioapptives'
        log_stream_name: '${POD_NAME}'
        namespace: 'Bioapptives'
        dimension_rollup_option: NoDimensionRollup
        log_retention: 30
        metric_declarations:
          - dimensions: [[Namespace]]
            metric_name_selectors:
              - ErrorCount
      awsemf/marcador:
        region: '${AWS_REGION}'
        log_group_name: '/aws/eks/${CLUSTER_NAME}/marcador'
        log_stream_name: '${POD_NAME}'
        namespace: 'Marcador'
        dimension_rollup_option: NoDimensionRollup
        log_retention: 30
        metric_declarations:
          - dimensions: [[Namespace]]
            metric_name_selectors:
              - ErrorCount
    service:
      pipelines:
        logs/bioapptives:
          receivers: [otlp]
          processors: [batch, filterprocessor/namespace_bioapptives]
          exporters: [awsemf/bioapptives]
        logs/bioapptives_errors:
          receivers: [otlp]
          processors: [batch, filterprocessor/namespace_bioapptives, filterprocessor/errors]
          exporters: [awsemf/bioapptives]
        logs/marcador:
          receivers: [otlp]
          processors: [batch, filterprocessor/namespace_marcador]
          exporters: [awsemf/marcador]
        logs/marcador_errors:
          receivers: [otlp]
          processors: [batch, filterprocessor/namespace_marcador, filterprocessor/errors]
          exporters: [awsemf/marcador]
