apiVersion: v1
kind: ConfigMap
metadata:
  name: adot-collector-config
  namespace: fargate-container-insights
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
      filter:
        logs:
          strict_match: false
          include:
            match_type: regexp
            expressions:
              - value: ".*(OperationalError|Name or service not known|Connection reset by peer).*"
    exporters:
      awsemf:
        region: ''
        log_group_name: '/aws/eks//bioapptives'
        log_stream_name: ''
        namespace: 'Bioapptives'
        dimension_rollup_option: NoDimensionRollup
        log_retention: 30
    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [batch, filter]
          exporters: [awsemf]
