apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: bioapptives
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level    info
        Daemon       off

    [INPUT]
        Name             tail
        Path             /var/log/containers/*_bioapptives_*.log
        Parser           docker
        Tag              kube.*
        Refresh_Interval 10
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL           https://kubernetes.default.svc:443
        Kube_CA_File       /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File    /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log          On
        K8S-Logging.Parser On

    [OUTPUT]
        Name            opentelemetry
        Match           *
        Host            adot-collector.fargate-container-insights.svc
        Port            4318
        Logs_uri        /v1/logs
        Log_response_payload True

    [PARSER]
        Name   docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
